### ISSUE TITLE
sass-loader@8.0.0 requires a peer of fibers@>= 3.1.0 but none is installed. You must install peer dependencies yourself.

### ISSUE THREAD

**Issue by dav11d** [entozoon/slatest-example#1]
Any idea how to resolve this when installing ? Windows with gitbash

Trying to run npm start with wsl nix/subsystem also run into

/SLATEST/node_modules/slatest/lib/config.js:23
    throw new Error(
    ^

Error: Please create a /mnt/c/Users/D/SLATEST/slatest.config.json file in your project dir!

even thought it exists

**Comment by entozoon** [comment]
Did you figure it out @dav11d ? I haven't tested on a unix environment

**Comment by dav11d** [comment]
Hi @entozoon, no sorry - realised I posted in the wrong repo.
